# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


def update_links(item):
    if item['link']:
        if item['link']['link_text']:
            item['nav_link']['text'] = item['link']['link_text']
        if item['link']['page_link']:
            item['nav_link']['url'] = item['link']['page_link'].url
        elif item['link']['external_link']:
            item['nav_link']['url'] = item['link']['external_link']


def update_nav_items(block):
    for nav_item in block:
        update_links(nav_item)
        child_items = nav_item.get('nav_items')
        if child_items:
            update_nav_items(nav_item['nav_items'])


def update_menu_item_links(apps, schema_editor):
    MenuItem = apps.get_model('v1', 'MenuItem')

    for item in MenuItem.objects.all():
        if item.page_link:
            item.url = '/{}/'.format(item.page_link.slug)
        
        cols = [getattr(item, 'column_' + str(i)) for i in range(1, 5)]
        for col in cols:
            for block in col:
                if block.block_type == 'nav_group':
                    update_nav_items(block.value['nav_items'])
                elif block.block_type == 'featured_content':
                    update_links(block.value)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0152_remove_latest_updates_from_home_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='link_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, default=b'#', help_text=b'Link to Wagtail overview page for this menu item (leave blank if there is no overview page).', max_length=255, verbose_name=b'Overview page link'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='column_1',
            field=wagtail.wagtailcore.fields.StreamField([(b'nav_group', wagtail.wagtailcore.blocks.StructBlock([(b'draft', wagtail.wagtailcore.blocks.BooleanBlock(default=False, help_text=b'If checked, this block will only show on our sharing site (Content).', label=b'Mark block as draft', required=False)), (b'group_title', wagtail.wagtailcore.blocks.CharBlock(label=b'Column title', required=False)), (b'hide_group_title', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'If column shares title with previous column, enter title text above but check this box so title only shows in first column.', label=b'Hide column title', required=False)), (b'nav_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'state', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'both', b'Show always'), (b'live', b'Show on Production only'), (b'draft', b'Show on Content only')], help_text=b'Select state for this link. Test new links by setting them to only show on Content.')), (b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock(label=b'Text', required=True)), (b'page_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text=b'Link to a page in Wagtail.', label=b'Page', required=False)), (b'external_link', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Enter url for page outside Wagtail. This will only be used if there is no page selected.', label=b'Direct URL (rare)', max_length=1000, required=False))], required=False)), (b'nav_link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))])), (b'nav_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock(label=b'Text', required=True)), (b'page_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text=b'Link to a page in Wagtail.', label=b'Page', required=False)), (b'external_link', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Enter url for page outside Wagtail. This will only be used if there is no page selected.', label=b'Direct URL (rare)', max_length=1000, required=False))])), (b'nav_link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))]))]), label=b'Child items (mobile only)'))]), label=b'Menu items', required=False))], label=b'Menu items group'))], blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='column_2',
            field=wagtail.wagtailcore.fields.StreamField([(b'nav_group', wagtail.wagtailcore.blocks.StructBlock([(b'draft', wagtail.wagtailcore.blocks.BooleanBlock(default=False, help_text=b'If checked, this block will only show on our sharing site (Content).', label=b'Mark block as draft', required=False)), (b'group_title', wagtail.wagtailcore.blocks.CharBlock(label=b'Column title', required=False)), (b'hide_group_title', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'If column shares title with previous column, enter title text above but check this box so title only shows in first column.', label=b'Hide column title', required=False)), (b'nav_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'state', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'both', b'Show always'), (b'live', b'Show on Production only'), (b'draft', b'Show on Content only')], help_text=b'Select state for this link. Test new links by setting them to only show on Content.')), (b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock(label=b'Text', required=True)), (b'page_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text=b'Link to a page in Wagtail.', label=b'Page', required=False)), (b'external_link', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Enter url for page outside Wagtail. This will only be used if there is no page selected.', label=b'Direct URL (rare)', max_length=1000, required=False))], required=False)), (b'nav_link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))])), (b'nav_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock(label=b'Text', required=True)), (b'page_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text=b'Link to a page in Wagtail.', label=b'Page', required=False)), (b'external_link', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Enter url for page outside Wagtail. This will only be used if there is no page selected.', label=b'Direct URL (rare)', max_length=1000, required=False))])), (b'nav_link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))]))]), label=b'Child items (mobile only)'))]), label=b'Menu items', required=False))], label=b'Menu items group'))], blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='column_3',
            field=wagtail.wagtailcore.fields.StreamField([(b'nav_group', wagtail.wagtailcore.blocks.StructBlock([(b'draft', wagtail.wagtailcore.blocks.BooleanBlock(default=False, help_text=b'If checked, this block will only show on our sharing site (Content).', label=b'Mark block as draft', required=False)), (b'group_title', wagtail.wagtailcore.blocks.CharBlock(label=b'Column title', required=False)), (b'hide_group_title', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'If column shares title with previous column, enter title text above but check this box so title only shows in first column.', label=b'Hide column title', required=False)), (b'nav_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'state', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'both', b'Show always'), (b'live', b'Show on Production only'), (b'draft', b'Show on Content only')], help_text=b'Select state for this link. Test new links by setting them to only show on Content.')), (b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock(label=b'Text', required=True)), (b'page_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text=b'Link to a page in Wagtail.', label=b'Page', required=False)), (b'external_link', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Enter url for page outside Wagtail. This will only be used if there is no page selected.', label=b'Direct URL (rare)', max_length=1000, required=False))], required=False)), (b'nav_link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))])), (b'nav_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock(label=b'Text', required=True)), (b'page_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text=b'Link to a page in Wagtail.', label=b'Page', required=False)), (b'external_link', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Enter url for page outside Wagtail. This will only be used if there is no page selected.', label=b'Direct URL (rare)', max_length=1000, required=False))])), (b'nav_link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))]))]), label=b'Child items (mobile only)'))]), label=b'Menu items', required=False))], label=b'Menu items group'))], blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='column_4',
            field=wagtail.wagtailcore.fields.StreamField([(b'nav_group', wagtail.wagtailcore.blocks.StructBlock([(b'draft', wagtail.wagtailcore.blocks.BooleanBlock(default=False, help_text=b'If checked, this block will only show on our sharing site (Content).', label=b'Mark block as draft', required=False)), (b'group_title', wagtail.wagtailcore.blocks.CharBlock(label=b'Column title', required=False)), (b'hide_group_title', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'If column shares title with previous column, enter title text above but check this box so title only shows in first column.', label=b'Hide column title', required=False)), (b'nav_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'state', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'both', b'Show always'), (b'live', b'Show on Production only'), (b'draft', b'Show on Content only')], help_text=b'Select state for this link. Test new links by setting them to only show on Content.')), (b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock(label=b'Text', required=True)), (b'page_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text=b'Link to a page in Wagtail.', label=b'Page', required=False)), (b'external_link', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Enter url for page outside Wagtail. This will only be used if there is no page selected.', label=b'Direct URL (rare)', max_length=1000, required=False))], required=False)), (b'nav_link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))])), (b'nav_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock(label=b'Text', required=True)), (b'page_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text=b'Link to a page in Wagtail.', label=b'Page', required=False)), (b'external_link', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Enter url for page outside Wagtail. This will only be used if there is no page selected.', label=b'Direct URL (rare)', max_length=1000, required=False))])), (b'nav_link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))]))]), label=b'Child items (mobile only)'))]), label=b'Menu items', required=False))], label=b'Menu items group')), (b'featured_content', wagtail.wagtailcore.blocks.StructBlock([(b'draft', wagtail.wagtailcore.blocks.BooleanBlock(default=False, help_text=b'If checked, this block will only show on our sharing site (Content).', label=b'Mark block as draft', required=False)), (b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock(label=b'Text', required=True)), (b'page_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text=b'Link to a page in Wagtail.', label=b'Page', required=False)), (b'external_link', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Enter url for page outside Wagtail. This will only be used if there is no page selected.', label=b'Direct URL (rare)', max_length=1000, required=False))], label=b'H4 link', required=False)), (b'nav_link', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.CharBlock(default=b'/', required=False))])), (b'body', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), (b'image', wagtail.wagtailcore.blocks.StructBlock([(b'upload', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'alt', wagtail.wagtailcore.blocks.CharBlock(help_text=b"If the image is decorative (i.e., if a screenreader wouldn't have anything useful to say about it), leave the Alt field blank.", required=False))]))], label=b'Featured image item'))], blank=True),
        ),
        migrations.RunPython(update_menu_item_links),
    ]
